document.addEventListener('DOMContentLoaded', () => {
  const stylesheet = document.createElement('link');
  stylesheet.rel = 'stylesheet';
  stylesheet.href = 'css/rental-review.css';
  document.head.appendChild(stylesheet);
  const cardStyle = document.createElement('style');
  cardStyle.textContent = '.work>.featured-project+.featured-project{margin-top:32px}.work>.featured-project .project-visual{height:520px;min-height:520px}.work>.featured-project .project-visual img{object-fit:cover}@media(max-width:760px){.work>.featured-project+.featured-project{margin-top:22px}.work>.featured-project .project-visual{height:310px;min-height:310px}}';
  document.head.appendChild(cardStyle);

  const work = document.querySelector('#work');
  if (!work) return;

  const asset = name => name === 'image11.png' ? 'assets/rental/cover.png' : 'assets/rental/' + name;
  const section = (number, title, intro, body) => '<section class="rental-section"><div class="rental-heading"><span>' + number + '</span><div><h3>' + title + '</h3><p>' + intro + '</p></div></div>' + body + '</section>';
  const table = (headers, rows) => '<div class="rental-table-wrap"><table class="rental-table"><thead><tr>' + headers.map(x => '<th>' + x + '</th>').join('') + '</tr></thead><tbody>' + rows.map(row => '<tr>' + row.map(x => '<td>' + x + '</td>').join('') + '</tr>').join('') + '</tbody></table></div>';
  const image = (name, alt, caption) => '<figure><img src="' + asset(name) + '" alt="' + alt + '"><figcaption>' + caption + '</figcaption></figure>';

  const card = document.createElement('article');
  card.className = 'featured-project rental-project';
  card.innerHTML = '<div class="project-visual"><div class="visual-label">CASE 03 / 2026</div><img src="' + asset('image11.png') + '" alt="出租屋数字孪生实景看房"><div class="visual-caption">鸿蒙智能出租房<br><small>DIGITAL TWIN × IOT × PUBLIC SERVICE</small></div></div><div class="project-content"><p class="project-kicker">案例 03 · 数字孪生与软硬协同</p><h3>鸿蒙智能出租房</h3><p class="project-title">把一套出租屋，变成可计算、可协同、可追溯的数字资产</p><p class="project-desc">面向租客、房东、中介与政府的流动人员管控平台，以 1:1 数字孪生、智能硬件、AI 评分和政务协同，覆盖租前核验、租中监控、租后结算与风险处置。</p><div class="tag-row"><span>HarmonyOS</span><span>数字孪生</span><span>IoT</span><span>智慧租房</span></div><div class="project-meta"><div><small>项目呈现</small><b>产品策略 · 系统架构 · 交互证据</b></div><div><small>项目材料</small><b>论文拆解 + 业务指标 + 页面原型</b></div></div><a class="button dark case-toggle" href="#case-rental" data-case="case-rental" aria-expanded="false">展开案例 <span>↓</span></a></div>';
  work.append(card);

  const panel = document.createElement('section');
  panel.id = 'case-rental';
  panel.className = 'case-panel rental-case wrap';

  const hero = '<div class="rental-review-hero"><div><p class="eyebrow">CASE STUDY / HARMONYOS RENTAL</p><h2>把一套出租屋，<br>变成可计算、可协同、可追溯的数字资产</h2><p class="rental-review-lead">项目围绕租客、房东、中介和政府四类角色，构建“租前风险筛查 → 租中动态监控 → 租后无忧结算 → 政府协同管控”的全链条服务。我的产品判断是：数字孪生不是 3D 展示，而是把空间、设备、人员和政务流程绑定到同一套可验证数据上。</p><div class="rental-tags"><span>HarmonyOS</span><span>数字孪生</span><span>端边云协同</span><span>政务服务</span><span>IoT</span></div></div><div class="rental-highlights"><div><b>37% → 5%</b><span>论文披露：虚假房源率</span></div><div><b>80%</b><span>线下看房时间节省目标</span></div><div><b>35% → 8%</b><span>租金拖欠率改善目标</span></div><div><b>2 小时</b><span>城区维修响应承诺</span></div><div><b>100%</b><span>在逃人员拦截率（方案披露）</span></div><div><b>40%</b><span>签约转化提升目标</span></div></div></div><div class="rental-materials"><span>鸿蒙智能出租房 · AI 产品经理项目复盘</span><div><button class="material-button" data-material="鸿蒙智能出租房完整论文">完整论文</button><button class="material-button" data-material="鸿蒙智能出租房项目材料">项目材料</button></div></div>';

  const context = section('01', '项目机会：租房不是一次交易，而是一条长期风险链', '论文把行业问题拆成“信息不透明、安全不可验证、设备不可控、政府难协同”四个断点。产品机会不是再做一个房源列表，而是让每个角色都拥有可解释的状态与动作。', '<div class="rental-two"><article class="rental-card"><h4>租客：从“看起来不错”到“住得安心”</h4><ul><li>68% 租客遭遇过照片与实物不符，虚假房源与信息差直接影响决策。</li><li>女性租客、合租人群更关注门禁、陌生人预警、隐私与退租举证。</li><li>目标：3D 实景核验、背景核验、异常预警、维修追踪和押金争议留痕。</li></ul></article><article class="rental-card"><h4>房东 / 中介 / 政府：从“人肉管理”到“状态协同”</h4><ul><li>房东需要批量管理、自动收租、维修调度和空置率预测。</li><li>中介需要可信房源展示，减少带看成本并提高签约转化。</li><li>政府需要人口、消防、房源和风险事件的跨部门管控闭环。</li></ul></article></div><div class="rental-media"><' + image('image70.png','目标租客群体分布图','目标租客群体：学生 25%、应届生 20%、上班族 30%、单身青年 15%、家庭租户 10%。') + image('image12.png','数字孪生核心价值评分图','价值拆解：真实感、实时性和政务协同分别从用户侧与运营侧体现价值。') + '</div>');

  const architecture = section('02', '系统架构：让设备数据、空间模型与政务流程在同一张图上汇合', '产品架构采用硬件层、数据层、政务协同层和专利技术层分层设计。对产品经理而言，关键不是罗列技术，而是明确每一层产出的数据如何被下一层消费。', '<div class="rental-architecture"><img src="' + asset('image1.png') + '" alt="系统架构分层图"></div><div class="rental-feature-grid"><article><b>硬件层 · 采集事实</b><p>智能门锁、烟感器、1080P 夜视摄像头和水电表负责采集门禁、安全、能耗和人员流动信号。</p></article><article><b>数据层 · 形成状态</b><p>边缘计算节点先做本地响应，数据预处理统一图像与传感器格式，再由人口库与分析引擎形成可查询状态。</p></article><article><b>政务协同层 · 触发动作</b><p>公安、消防、高风险名单与平台管控闭环形成跨部门处置路径，应用层服务租客端、房东端和政务端。</p></article></div><div class="rental-media">' + image('image2.png','智能门锁硬件拆解','防暴智能门锁：身份识别、权限控制与断网可用是入住安全的基础。') + image('image3.png','烟感报警器','高灵敏度烟感器：以环境感知驱动火灾预警与设备联动。') + image('image4.png','智能摄像头','智能摄像头：视频采集、行为识别、陌生脸预警与门禁联动。') + '</div>');

  const value = section('03', '数字孪生：从“看房模型”升级为“运营事实层”', '项目将三维点云建模、实时数据映射和政务数据连接起来，让模型不只展示空间，还能承载设备状态、瑕疵记录、空气质量和消防路径。', '<div class="rental-flow"><div><small>01 · 物理空间</small><b>房屋、家具、门锁、烟感、摄像头与能耗设备</b></div><div><small>02 · 数字空间</small><b>1:1 房屋模型、设施标注、历史状态与可交互看房</b></div><div><small>03 · 实时同步</small><b>门锁开关、报警信息、人员轨迹与维修状态</b></div><div><small>04 · 政务沙盘</small><b>消防路线、群租密度、风险事件与跨部门处置</b></div></div><div class="rental-media">' + image('image11.png','出租屋数字孪生实景看房','数字孪生模型支持旋转、放大和细节标注，连接房屋真实结构与远程看房。') + image('image54.png','三维点云模型','点云数据用于还原户型、家具边缘和设施位置，为网格化建模提供输入。') + image('image58.png','点云网格化结果','泊松重建与深度学习双路径融合，追求全局平滑与局部细节兼顾。') + image('image61.png','三维空间特征可视化','从点云特征到空间表达，为后续设施定位和异常标注提供基础。') + '</div><div class="rental-note"><b>产品判断</b>模型的价值不在“像不像”，而在每个空间对象是否能绑定责任人、状态、证据和下一步动作。</div>');

  const workflow = section('04', '产品闭环：用一套状态机覆盖租前、租中、租后与政府管控', '把论文中的功能清单整理成可执行的用户流：每个节点都有输入、判断、动作和留痕，避免数字孪生停留在展示层。', '<div class="rental-flow"><div><small>租前 · 核验</small><b>房源 12 维评分、数字孪生看房、租客身份与风险核验</b></div><div><small>租中 · 感知</small><b>门锁记录、烟感告警、摄像头异常识别、设备状态同步</b></div><div><small>租后 · 结算</small><b>区块链分账、自动扣款、退租状态比对和维修工单</b></div><div><small>政府 · 协同</small><b>公安 / 消防数据接口、风险名单与应急处置闭环</b></div></div><div class="rental-feature-grid"><article><b>AI 房源评分</b><p>TensorFlow + ResNet-50 处理墙面裂缝、图片真实性与交通便利性等 12 类特征，输出可解释评分。</p></article><article><b>异常行为分析</b><p>目标检测、行为识别、BERT 文本分析与 LSTM 时序建模共同支持风险预警，但高风险动作必须保留人工复核。</p></article><article><b>软硬协同</b><p>端侧先响应门锁与烟感，边缘端降低延迟，云端承载存储、跨设备比对和运营分析。</p></article></div><div class="rental-media"><' + image('image71.png','项目技术与业务指标图','指标图展示匹配效率、故障响应与运营效率等目标变化。') + image('image72.png','系统能力雷达图','从感知、实时、协同、安全和运营等维度观察产品能力结构。') + '</div>');

  const screens = section('05', '页面证据：不同角色看到不同的状态与动作', '页面不是功能堆叠，而是围绕“我现在需要处理什么”组织信息：租客快速入住与报修，房东批量管理，运营人员查看统计，管理员回放证据。', '<div class="rental-media rental-phone-grid">' + image('image77.png','租客端房源与发布页面','租客端：房源浏览、发布与快速进入房屋服务。') + image('image78.png','租客端房源详情与数字孪生入口','房源详情：把房屋信息、设施与看房动作放在同一条路径。') + image('image79.png','平台首页功能入口','首页：租客登记、远程开门、房屋管理、设备管理和账单管理。') + image('image80.png','房源筛选页面','房源筛选：通过标签和结构化条件降低找房成本。') + image('image81.png','云端找房首页','云端找房：以房源卡片和状态信息建立可信入口。') + image('image82.png','运营统计首页','运营首页：新增房屋、租客、异常人员和异常设备一屏可见。') + image('image83.png','房屋管理页面','房屋管理：批量查看房间、租客、服务期和租客登记动作。') + image('image84.png','监控回放页面','监控回放：按日期检索视频证据，支撑异常追溯和运营复盘。') + '</div>');

  const metrics = section('06', '指标与验证：把目标、对比和证据分开看', '论文同时给出业务目标、技术指标与场景对比。作品集中将其分为“方案披露”与“需要持续验证”两类，保持产品判断的可信度。', '<div class="rental-media">' + image('image8.png','传统平台与本项目故障响应时间对比','故障响应对比：门锁断网、烟感误报、摄像头离线和系统卡顿均显著缩短。') + image('image87.png','项目指标对比图','项目披露的指标对比：围绕响应、效率和安全建立验证框架。') + '</div>' + table(['指标维度','论文披露 / 目标','产品化验收方式'], [['房源可信度','虚假房源率 37% → 5%；数字孪生应用后披露低于 1%','抽样核验真实房源、模型标注与用户投诉闭环'],['看房效率','线下看房时间节省 80%；签约转化 +40%','记录从首次浏览到签约的漏斗与分角色对照组'],['安全响应','摄像头离线 5h → 45m；烟感误报 3h → 15m','按事件级别统计发现、确认、处置、恢复四段时延'],['运营效率','匹配效率 +60%；空置期缩短 30%','观察推荐采纳、房源上线、空置天数和维修完成率'],['租后结算','拖欠率 35% → 8%；押金争议率下降','对账成功率、逾期率、退租状态证据完整度']]) + '<div class="rental-note"><b>合规底线</b>涉及身份、人脸、轨迹和政务数据时，必须采用最小化采集、脱敏展示、授权访问、可撤回与人工复核；高风险标签不能直接替代人工判断。</div>');

  const business = section('07', '商业闭环：硬件驱动服务增值，数据能力反哺运营', '项目提出“硬件驱动 + 服务增值 + 数据变现 + 流量运营”的四位一体模式。作为产品经理，我会先验证硬件套餐与维修服务的付费意愿，再逐步开放数据产品。', table(['产品 / 服务','配置或定价','核心价值'], [['基础版','智能门锁；成本 180 元 / 定价 499 元；毛利率 64%','合规入住与基础身份核验'],['安防版','门锁 + 烟感 + 1080P 摄像头；定价 1299 元；毛利率 63%','安全监控与火情联动'],['尊享版','全屋 4 件套；定价 2499 元；毛利率 65%','能耗预警与数字家庭示范'],['服务增值','保洁 129 元 / 次、消杀 299 元 / 次、基础维修 99 元 / 年','围绕退租、入住和设备维护变现'],['会员订阅','房东基础 29 元 / 月、Pro 199 元 / 月、机构黑金 599 元 / 月','提升曝光、维修折扣与合规报表']]) + '<div class="rental-media">' + image('image73.png','技术分层与业务价值图','从底层技术、平台能力到用户价值的分层关系。') + image('image96.png','三年战略规划图','规划目标：覆盖城市、收入和累计用户规模逐年增长。') + '</div>');

  const reflection = section('08', '复盘与下一步：从论文方案走向可验证的产品系统', '论文已经把技术、业务和社会效益铺开，下一步要把宏大叙事压缩成可试点、可度量、可合规的产品节奏。', '<div class="rental-two"><article class="rental-card"><h4>第一阶段：先证明“可信房源 + 快速处置”</h4><p>选取单楼栋试点，优先验证房源模型、门锁 / 烟感接入、故障响应和维修闭环；不急于扩张复杂的政务直连与数据变现。</p></article><article class="rental-card"><h4>第二阶段：再证明“数字孪生带来的经营价值”</h4><p>对照普通房源页，观察看房完成率、签约转化、维修时延、退租争议与房东续费率，建立可复用的 ROI 模型。</p></article><article class="rental-card"><h4>第三阶段：建立安全与合规护栏</h4><p>将人脸、轨迹、风险名单与政务数据拆成独立权限域，提供租客隐私中心、数据访问日志、人工申诉和模型偏差审计。</p></article><article class="rental-card"><h4>产品结论</h4><p>真正的壁垒不是“能做 3D”，而是把空间事实、设备状态、业务流程和公共服务组织成一套可解释、可追溯的运营系统。</p></article></div><button class="rental-close case-close" data-case="case-rental">收起案例 ↑</button>');

  panel.innerHTML = hero + context + architecture + value + workflow + screens + metrics + business + reflection;
  const nanxi = document.querySelector('#case-nanxi');
  if (nanxi) nanxi.after(panel); else work.after(panel);
});
